# default.yaml
camera_calib: "configs/cam_calib.yaml"

dataloader_config:
  base_path: "/workspace/Bench2Drive/eval_v1"
  # scenearios: "all"
  scenarios:
    - "scenario_1"
    - "scenario_2"
  output_path: "/workspace/Bench2Drive/eval_v1_output"
  cameras:
    - rgb_front
    - bev

analyze_config:
  # Specify which analyzer to use ("default" or "trajectory", etc.)
  type: "DefaultAnalyzer"
  visualize: true

visualizer_config:
  enable: true
  style: "default"  # could be "default", "advanced", etc.
  cameras:
    - rgb_front
    - bev

  output_video: true  # whether to generate video
  video_generator:
    # Output path for generated video
    output_path: "analysis_video.mp4"
    # Frames per second for the output video
    fps: 30

  # Which elements to visualize (list of strings)
  elements:
    - planned_trajectory
    - predicted_trajectory
    - bounding_box
