# default.yaml
cameras: "/workspace/Bench2Drive/tools/analyze_tool/configs/cameras_config.yaml"

dataloader_config:
  base_path: "/workspace/Bench2Drive/eval_v1"
  # scenearios: "all"
  scenarios:
    - "RouteScenario_3074_rep0_Town12_HighwayCutIn_1_0_01_30_09_19_14"
  output_path: "/workspace/Bench2Drive/eval_v1_output"

analyze_config:
  # Specify which analyzer to use ("default" or "trajectory", etc.)
  type: "DefaultAnalyzer"
  visualize: true

visualizer_config:
  enable: true
  style: "default"  # could be "default", "advanced", etc.
  cameras:
    - rgb_front
    - bev

  output_video: false  # whether to generate video
  video_generator:
    # Output path for generated video
    output_path: "analysis_video.mp4"
    # Frames per second for the output video
    fps: 30

  # Which elements to visualize (list of strings)
  elements:
    # - planned_trajectory
    # - predicted_trajectory
    - bbox_3d
    # - bbox_bev
